theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"ö" = "goto_prev_paragraph"
"ä" = "goto_next_paragraph"
